// THIS FILE IS AUTOGENERATED FROM base/tests/rpc/echo.proto

#ifndef BASE_RPC_ECHO_SERVICE_IF_DOT_H
#define BASE_RPC_ECHO_SERVICE_IF_DOT_H

#include "base/tests/rpc/echo.pb.h"

#include <functional>
#include <memory>
#include <string>

#include "base/rpc/rpc_header.pb.h"
#include "base/rpc/service_if.h"

namespace base {
class MetricEntity;
namespace rpc {
class Messenger;
class ResultTracker;
class RpcContext;
} // namespace rpc
} // namespace base

namespace base {
namespace echo_service {

class EchoServiceIf : public ::base::rpc::GeneratedServiceIf {
 public:
  explicit EchoServiceIf(const scoped_refptr<::base::MetricEntity>& entity, const scoped_refptr<::base::rpc::ResultTracker>& result_tracker);
  virtual ~EchoServiceIf();
  std::string service_name() const override;
  static std::string static_service_name();

  virtual void Echo(const EchoRequestPB *req,
     EchoResponsePB *resp, ::base::rpc::RpcContext *context) = 0;

};

} // namespace echo_service
} // namespace base

#endif
