// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base/tests/rpc/echo.proto

#ifndef PROTOBUF_base_2ftests_2frpc_2fecho_2eproto__INCLUDED
#define PROTOBUF_base_2ftests_2frpc_2fecho_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "base/rpc/rpc_header.pb.h"
// @@protoc_insertion_point(includes)

namespace base {
namespace echo_service {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_base_2ftests_2frpc_2fecho_2eproto();
void protobuf_AssignDesc_base_2ftests_2frpc_2fecho_2eproto();
void protobuf_ShutdownFile_base_2ftests_2frpc_2fecho_2eproto();

class EchoRequestPB;
class EchoResponsePB;

// ===================================================================

class EchoRequestPB : public ::google::protobuf::Message {
 public:
  EchoRequestPB();
  virtual ~EchoRequestPB();

  EchoRequestPB(const EchoRequestPB& from);

  inline EchoRequestPB& operator=(const EchoRequestPB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EchoRequestPB& default_instance();

  void Swap(EchoRequestPB* other);

  // implements Message ----------------------------------------------

  EchoRequestPB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EchoRequestPB& from);
  void MergeFrom(const EchoRequestPB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string message = 1;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 1;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:base.echo_service.EchoRequestPB)
 private:
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* message_;
  friend void  protobuf_AddDesc_base_2ftests_2frpc_2fecho_2eproto();
  friend void protobuf_AssignDesc_base_2ftests_2frpc_2fecho_2eproto();
  friend void protobuf_ShutdownFile_base_2ftests_2frpc_2fecho_2eproto();

  void InitAsDefaultInstance();
  static EchoRequestPB* default_instance_;
};
// -------------------------------------------------------------------

class EchoResponsePB : public ::google::protobuf::Message {
 public:
  EchoResponsePB();
  virtual ~EchoResponsePB();

  EchoResponsePB(const EchoResponsePB& from);

  inline EchoResponsePB& operator=(const EchoResponsePB& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EchoResponsePB& default_instance();

  void Swap(EchoResponsePB* other);

  // implements Message ----------------------------------------------

  EchoResponsePB* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EchoResponsePB& from);
  void MergeFrom(const EchoResponsePB& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string message = 1;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 1;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:base.echo_service.EchoResponsePB)
 private:
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* message_;
  friend void  protobuf_AddDesc_base_2ftests_2frpc_2fecho_2eproto();
  friend void protobuf_AssignDesc_base_2ftests_2frpc_2fecho_2eproto();
  friend void protobuf_ShutdownFile_base_2ftests_2frpc_2fecho_2eproto();

  void InitAsDefaultInstance();
  static EchoResponsePB* default_instance_;
};
// ===================================================================


// ===================================================================

// EchoRequestPB

// required string message = 1;
inline bool EchoRequestPB::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EchoRequestPB::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EchoRequestPB::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EchoRequestPB::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& EchoRequestPB::message() const {
  // @@protoc_insertion_point(field_get:base.echo_service.EchoRequestPB.message)
  return *message_;
}
inline void EchoRequestPB::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:base.echo_service.EchoRequestPB.message)
}
inline void EchoRequestPB::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:base.echo_service.EchoRequestPB.message)
}
inline void EchoRequestPB::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:base.echo_service.EchoRequestPB.message)
}
inline ::std::string* EchoRequestPB::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:base.echo_service.EchoRequestPB.message)
  return message_;
}
inline ::std::string* EchoRequestPB::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void EchoRequestPB::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:base.echo_service.EchoRequestPB.message)
}

// -------------------------------------------------------------------

// EchoResponsePB

// required string message = 1;
inline bool EchoResponsePB::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EchoResponsePB::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EchoResponsePB::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EchoResponsePB::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& EchoResponsePB::message() const {
  // @@protoc_insertion_point(field_get:base.echo_service.EchoResponsePB.message)
  return *message_;
}
inline void EchoResponsePB::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:base.echo_service.EchoResponsePB.message)
}
inline void EchoResponsePB::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:base.echo_service.EchoResponsePB.message)
}
inline void EchoResponsePB::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:base.echo_service.EchoResponsePB.message)
}
inline ::std::string* EchoResponsePB::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:base.echo_service.EchoResponsePB.message)
  return message_;
}
inline ::std::string* EchoResponsePB::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void EchoResponsePB::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:base.echo_service.EchoResponsePB.message)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace echo_service
}  // namespace base

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_base_2ftests_2frpc_2fecho_2eproto__INCLUDED
