// THIS FILE IS AUTOGENERATED FROM base/tests/rpc/echo.proto

#ifndef BASE_RPC_ECHO_PROXY_DOT_H
#define BASE_RPC_ECHO_PROXY_DOT_H

#include "base/tests/rpc/echo.pb.h"

#include "base/rpc/proxy.h"
#include "base/util/status.h"

namespace base { class Sockaddr; }
namespace base { namespace rpc { class UserCredentials; } }
namespace base {
namespace echo_service {


class EchoServiceProxy : public ::base::rpc::Proxy {
 public:
  EchoServiceProxy(const std::shared_ptr< ::base::rpc::Messenger>
                &messenger, const ::base::Sockaddr &sockaddr);
  ~EchoServiceProxy();


  ::base::Status Echo(const EchoRequestPB &req, EchoResponsePB *resp,
                          ::base::rpc::RpcController *controller);
  void EchoAsync(const EchoRequestPB &req,
                       EchoResponsePB *response,
                       ::base::rpc::RpcController *controller,
                       const ::base::rpc::ResponseCallback &callback);
};

} // namespace echo_service
} // namespace base

#endif
